name: MoT
favicon: null
layout_spectrum: 0.48831
typography_spectrum: 0.49332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6202b'
    - '#ffffff'
    - '#314ea2'
    - '#5a1245'
    - '#fec20e'
  brandStrength: 0.36667899251915514
  lightness: 0.27213145256973803
  saturation: 0.5190302261617035
  rhythmicContrast: 0.1444775650743395
purpose: []
